const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('jarvis', {
  onActivated: (cb) => ipcRenderer.on('jarvis:activated', (_e, payload) => cb(payload)),
  transcribe: (audioBase64) => ipcRenderer.invoke('jarvis:transcribe', audioBase64),
  chat: (message, history) => ipcRenderer.invoke('jarvis:chat', { message, history }),
  speak: (text) => ipcRenderer.invoke('jarvis:speak', text),
  openFile: () => ipcRenderer.invoke('jarvis:openFile'),
  notify: (title, body) => ipcRenderer.invoke('jarvis:notify', { title, body }),
  hide: () => ipcRenderer.invoke('jarvis:hide'),
  authSignup: (d) => ipcRenderer.invoke('auth:signup', d),
  authLogin: (d) => ipcRenderer.invoke('auth:login', d),
  authVerify: () => ipcRenderer.invoke('auth:verify'),
  authGoogle: () => ipcRenderer.invoke('auth:google'),
  authLogout: () => ipcRenderer.invoke('auth:logout'),
  authGetToken: () => ipcRenderer.invoke('auth:getToken'),
  onGoogleSuccess: (cb) => ipcRenderer.on('auth:google-success', (_e, d) => cb(d)),
  getProfile: () => ipcRenderer.invoke('profile:get'),
  setProfile: (profile) => ipcRenderer.invoke('profile:set', profile),
  getMemories: () => ipcRenderer.invoke('memory:get'),
  clearMemories: () => ipcRenderer.invoke('memory:clear'),
  saveSession: (s) => ipcRenderer.invoke('session:save', s),
  listSessions: () => ipcRenderer.invoke('session:list'),
  deleteSession: (id) => ipcRenderer.invoke('session:delete', id),
  getVoiceSpeed: () => ipcRenderer.invoke('voice:getSpeed'),
  setVoiceSpeed: (s) => ipcRenderer.invoke('voice:setSpeed', s),
  getContacts: () => ipcRenderer.invoke('contacts:get'),
  addContact: (c) => ipcRenderer.invoke('contacts:add', c),
  deleteContact: (id) => ipcRenderer.invoke('contacts:delete', id),
  callContact: (phone, platform) => ipcRenderer.invoke('contacts:call', { phone, platform }),
  openUrl: (url) => ipcRenderer.invoke('jarvis:openUrl', url),
  connectorStatus: () => ipcRenderer.invoke('connector:status'),
  connectorConnect: (service) => ipcRenderer.invoke('connector:connect', service),
  connectorDisconnect: (service) => ipcRenderer.invoke('connector:disconnect', service),
  connectorGetVip: () => ipcRenderer.invoke('connector:getVip'),
  connectorAddVip: (v) => ipcRenderer.invoke('connector:addVip', v),
  connectorRemoveVip: (v) => ipcRenderer.invoke('connector:removeVip', v),
  onConnectorConnected: (cb) => ipcRenderer.on('connector:connected', (_e, d) => cb(d)),
  getMusicService: () => ipcRenderer.sendSync('music:getService'),
  setMusicService: (s) => ipcRenderer.sendSync('music:setService', s),
  getLanguage: () => ipcRenderer.sendSync('language:get'),
  setLanguage: (lang) => ipcRenderer.sendSync('language:set', lang),
  onActionFired: (cb) => ipcRenderer.on('jarvis:action-fired', (_e, d) => cb(d)),
});
