const { contextBridge, ipcRenderer, webUtils } = require('electron');

// Real path of a dragged/picked File — File.path was removed in Electron 32.
function filePathOf(file) {
  try { return (webUtils && webUtils.getPathForFile(file)) || file.path || null; }
  catch (_) { return file.path || null; }
}

contextBridge.exposeInMainWorld('jarvis', {
  onActivated: (cb) => ipcRenderer.on('jarvis:activated', (_e, payload) => cb(payload)),
  transcribe: (audioBase64) => ipcRenderer.invoke('jarvis:transcribe', audioBase64),
  chat: (message, history, attachments) => ipcRenderer.invoke('jarvis:chat', { message, history, attachments: attachments || [] }),
  speak: (text) => ipcRenderer.invoke('jarvis:speak', text),
  openFile: () => ipcRenderer.invoke('jarvis:openFile'),
  notify: (title, body) => ipcRenderer.invoke('jarvis:notify', { title, body }),
  hide: () => ipcRenderer.invoke('jarvis:hide'),
  authSignup: (d) => ipcRenderer.invoke('auth:signup', d),
  authLogin: (d) => ipcRenderer.invoke('auth:login', d),
  authVerify: () => ipcRenderer.invoke('auth:verify'),
  authGoogle: () => ipcRenderer.invoke('auth:google'),
  authLogout: () => ipcRenderer.invoke('auth:logout'),
  // authGetToken intentionally removed — JWT must never cross the IPC bridge to renderer
  onGoogleSuccess: (cb) => ipcRenderer.on('auth:google-success', (_e, d) => cb(d)),
  onSubscriptionActivated: (cb) => ipcRenderer.on('subscription:activated', () => cb()),
  getProfile: () => ipcRenderer.invoke('profile:get'),
  setProfile: (profile) => ipcRenderer.invoke('profile:set', profile),
  getMemories: () => ipcRenderer.invoke('memory:get'),
  clearMemories: () => ipcRenderer.invoke('memory:clear'),
  saveSession: (s) => ipcRenderer.invoke('session:save', s),
  listSessions: () => ipcRenderer.invoke('session:list'),
  deleteSession: (id) => ipcRenderer.invoke('session:delete', id),
  getVoiceSpeed: () => ipcRenderer.invoke('voice:getSpeed'),
  setVoiceSpeed: (s) => ipcRenderer.invoke('voice:setSpeed', s),
  getContacts: () => ipcRenderer.invoke('contacts:get'),
  addContact: (c) => ipcRenderer.invoke('contacts:add', c),
  deleteContact: (id) => ipcRenderer.invoke('contacts:delete', id),
  callContact: (phone, platform) => ipcRenderer.invoke('contacts:call', { phone, platform }),
  openUrl: (url) => ipcRenderer.invoke('jarvis:openUrl', url),
  openApp: (name) => ipcRenderer.invoke('jarvis:openApp', name),
  openInAppBrowser: (url) => ipcRenderer.invoke('jarvis:openInAppBrowser', url),
  // Forward a quick-launch result to the HUD overlay (Ctrl+Shift+C mode)
  hudForward: (text, card) => ipcRenderer.invoke('jarvis:hudForward', { text, card }),
  openGoogleUrl: (url) => ipcRenderer.invoke('google:openUrl', url),
  placesNearby: (query, lat, lng, city) => ipcRenderer.invoke('places:nearby', { query, lat, lng, city }),
  openCheckout: (plan) => ipcRenderer.invoke('jarvis:openCheckout', plan),
  connectorStatus: () => ipcRenderer.invoke('connector:status'),
  connectorConnect: (service) => ipcRenderer.invoke('connector:connect', service),
  connectorDisconnect: (service) => ipcRenderer.invoke('connector:disconnect', service),
  connectorGetVip: () => ipcRenderer.invoke('connector:getVip'),
  connectorAddVip: (v) => ipcRenderer.invoke('connector:addVip', v),
  connectorRemoveVip: (v) => ipcRenderer.invoke('connector:removeVip', v),
  onConnectorConnected: (cb) => ipcRenderer.on('connector:connected', (_e, d) => cb(d)),
  onConnectorWrongAccount: (cb) => ipcRenderer.on('connector:wrongAccount', (_e, d) => cb(d)),
  onMacNeedsAutomation: (cb) => ipcRenderer.on('mac:needsAutomation', () => cb()),
  openMacPrivacySettings: (pane) => ipcRenderer.invoke('mac:openPrivacySettings', pane),
  onPowerSleep: (cb) => ipcRenderer.on('power:sleep', () => cb()),
  onPowerWake:  (cb) => ipcRenderer.on('power:wake', () => cb()),
  getMusicService: () => ipcRenderer.sendSync('music:getService'),
  setMusicService: (s) => ipcRenderer.sendSync('music:setService', s),
  getLanguage: () => ipcRenderer.sendSync('language:get'),
  setLanguage: (lang) => ipcRenderer.sendSync('language:set', lang),
  onActionFired: (cb) => ipcRenderer.on('jarvis:action-fired', (_e, d) => cb(d)),
  onVoiceTrigger: (cb) => ipcRenderer.on('jarvis:voice-trigger', () => cb()),
  onHudVoiceTrigger: (cb) => ipcRenderer.on('jarvis:hud-voice-trigger', () => cb()),
  onHudResponse: (cb) => ipcRenderer.on('jarvis:hud-response', (_e, d) => cb(d)),
  onSentenceAudio: (cb) => ipcRenderer.on('jarvis:sentence-audio', (_e, d) => cb(d)),
  onSentenceText: (cb) => ipcRenderer.on('jarvis:sentence-text', (_e, d) => cb(d)),
  driveSearch: (query) => ipcRenderer.invoke('drive:search', query),
  driveOpen: (fileId, mimeType, webViewLink) => ipcRenderer.invoke('drive:open', { fileId, mimeType, webViewLink }),
  analyticsGet: (platform) => ipcRenderer.invoke('analytics:get', platform || 'all'),
  reminderList: () => ipcRenderer.invoke('reminder:list'),
  reminderAdd: (r) => ipcRenderer.invoke('reminder:add', r),
  reminderDelete: (id) => ipcRenderer.invoke('reminder:delete', id),
  taskList: () => ipcRenderer.invoke('task:list'),
  taskAdd: (text, date) => ipcRenderer.invoke('task:add', { text, date }),
  taskSetDone: (id, done) => ipcRenderer.invoke('task:setDone', { id, done }),
  taskDelete: (id) => ipcRenderer.invoke('task:delete', id),
  taskBriefing: () => ipcRenderer.invoke('task:briefing'),
  weatherGreeting: () => ipcRenderer.invoke('weather:greeting'),
  onTasksChanged: (cb) => ipcRenderer.on('jarvis:tasks-changed', () => cb()),
  onReminder: (cb) => ipcRenderer.on('jarvis:reminder', (_e, d) => cb(d)),
  calendarList: () => ipcRenderer.invoke('calendar:list'),
  calendarAdd: (event) => ipcRenderer.invoke('calendar:add', event),
  financeGetStock: (symbol) => ipcRenderer.invoke('finance:getStock', symbol),
  financeResolve: (query) => ipcRenderer.invoke('finance:resolve', query),
  financePortfolio: () => ipcRenderer.invoke('finance:portfolio'),
  financeAdd: (symbol) => ipcRenderer.invoke('finance:add', symbol),
  financeRemove: (symbol) => ipcRenderer.invoke('finance:remove', symbol),
  shopifyConnect: (shop, access_token) => ipcRenderer.invoke('shopify:connect', { shop, access_token }),
  squarespaceConnect: (api_key) => ipcRenderer.invoke('squarespace:connect', { api_key }),
  stripeConnect: (secret_key) => ipcRenderer.invoke('stripe:connect', { secret_key }),
  analyticsSelectProperty: (propertyId) => ipcRenderer.invoke('analytics:selectProperty', propertyId),
  onAnalyticsShowPropertyPicker: (cb) => ipcRenderer.on('analytics:showPropertyPicker', (_e, d) => cb(d)),
  // Auto-updater
  installUpdate: () => ipcRenderer.send('update:install'),
  onUpdateAvailable: (cb) => ipcRenderer.on('update:available', (_e, d) => cb(d)),
  onUpdateReady: (cb) => ipcRenderer.on('update:ready', () => cb()),
  sendEmail: (opts) => ipcRenderer.invoke('email:send', opts),
  saveWordDoc: (d) => ipcRenderer.invoke('jarvis:saveWordDoc', d),
  sheetOpen: (p) => ipcRenderer.invoke('sheet:open', p),
  sheetReveal: (p) => ipcRenderer.invoke('sheet:reveal', p),
  openGoogleDoc: (d) => ipcRenderer.invoke('jarvis:openGoogleDoc', d),
  addCalendarEvent: (d) => ipcRenderer.invoke('jarvis:addCalendarEvent', d),
  openGoogleSlides: (d) => ipcRenderer.invoke('jarvis:openGoogleSlides', d),
  onClipboardAI: (cb) => ipcRenderer.on('jarvis:clipboard-ai', (_e, d) => cb(d)),
  onNewsHeadlines: (cb) => ipcRenderer.on('jarvis:news-headlines', (_e, d) => cb(d)),
  // Tubes cursor: fetch a CDN script via main process (bypasses sandbox restriction)
  fetchCdnScript: (url) => ipcRenderer.invoke('util:fetchCdnScript', url),
  // Magic Editor
  magicEdit: (selectedText, instruction) => ipcRenderer.invoke('magic:edit', { selectedText, instruction }),
  onMagicEditStart: (cb) => ipcRenderer.on('jarvis:magic-edit-start', (_e, d) => cb(d)),
  onMagicEditStop: (cb) => ipcRenderer.on('jarvis:magic-edit-stop', () => cb()),
  magicEditEnded: () => ipcRenderer.send('magic:ended'),
  // 3D model generation
  modelEnabled:  () => ipcRenderer.invoke('model:enabled'),
  modelGenerate: (prompt, style, jobKey) => ipcRenderer.invoke('model:generate', { prompt, style, jobKey }),
  modelRetexture: (taskId, prompt, jobKey) => ipcRenderer.invoke('model:retexture', { taskId, prompt, jobKey }),
  saveModelFile: (bytes, suggestedName) => ipcRenderer.invoke('model:saveFile', { bytes, suggestedName }),
  fetchModelFile: (url) => ipcRenderer.invoke('model:fetchFile', url),
  artifactsList:   ()   => ipcRenderer.invoke('artifacts:list'),
  artifactsRemove: (id) => ipcRenderer.invoke('artifacts:remove', id),
  artifactsSave:   (id) => ipcRenderer.invoke('artifacts:save', { id }),
  onModelProgress: (cb) => ipcRenderer.on('model:progress', (_e, d) => cb(d)),
  onModelStart:  (cb) => ipcRenderer.on('model:start', (_e, d) => cb(d)),
  // Save a generated image or painting to disk
  saveImage:     (url, suggestedName) => ipcRenderer.invoke('media:saveImage', { url, suggestedName }),
  saveVideo:     (url, suggestedName) => ipcRenderer.invoke('media:saveVideo', { url, suggestedName }),
  // Publishing (only ever called after the customer confirms)
  publishRun:     (job)  => ipcRenderer.invoke('publish:run', job),
  publishTargets: ()     => ipcRenderer.invoke('publish:targets'),
  publishPickFile:(kind) => ipcRenderer.invoke('publish:pickFile', kind),
  filePath:       (file) => filePathOf(file),
  setLatestMedia: (kind, item) => ipcRenderer.invoke('media:setLatest', { kind, item }),
  getLatestMedia: ()           => ipcRenderer.invoke('media:getLatest'),
  // Shopping — real product results (images, prices) from the license server
  shopSearch:    (store, query, limit) => ipcRenderer.invoke('shop:search', { store, query, limit }),
  // AI phone calling — the assistant dials a business and negotiates on the user's behalf
  callStart:     (payload) => ipcRenderer.invoke('call:start', payload),
  callRespond:   (callId, approved, note) => ipcRenderer.invoke('call:respond', { callId, approved, note }),
  callHangup:    (callId) => ipcRenderer.invoke('call:hangup', { callId }),
  callEnabled:   () => ipcRenderer.invoke('call:enabled'),
  callHistory:   () => ipcRenderer.invoke('call:history'),
  onCallEvent:   (cb) => ipcRenderer.on('call:event', (_e, d) => cb(d)),
  // Quit app (used by gesture — clap = clear + quit)
  quitApp:       () => ipcRenderer.invoke('app:quit'),
  setAlwaysOnTop:   (flag) => ipcRenderer.invoke('app:setAlwaysOnTop', flag),
  setClickThrough:  (flag) => ipcRenderer.invoke('app:setClickThrough', flag),
  setUserLocation:  (loc)  => ipcRenderer.invoke('app:setUserLocation', loc),
  focusWindow:   () => ipcRenderer.invoke('app:focusWindow'),
  // HiggsField
  higgsSaveKey:  (key)    => ipcRenderer.invoke('higgsfield:saveKey', key),
  higgsGetKey:   ()       => ipcRenderer.invoke('higgsfield:getKey'),
  higgsGenerate: (opts)   => ipcRenderer.invoke('higgsfield:generate', opts),
  // Creative: painting + 3D
  generateImage: (prompt, size)    => ipcRenderer.invoke('creative:genimage', { prompt, size }),
  openPaint3D:   (subject, imageUrl) => ipcRenderer.invoke('creative:paint', { subject, imageUrl }),
  openBlender:   (subject)          => ipcRenderer.invoke('creative:blender', { subject }),

  // Spotify: renderer-side flow (fetch calls happen in renderer, main just provides token + OS actions)
  spotifyGetToken:  ()    => ipcRenderer.invoke('jarvis:spotifyGetToken'),
  spotifyLaunch:    ()    => ipcRenderer.invoke('jarvis:spotifyLaunch'),
  spotifySuppress:  ()    => ipcRenderer.invoke('jarvis:spotifySuppress'),
  spotifyOpenUri:   (uri) => ipcRenderer.invoke('jarvis:spotifyOpenUri', uri),
  // Legacy combined handler (kept for old builds still calling spotify:play)
  spotifyPlay: (query) => ipcRenderer.invoke('jarvis:spotifyPlay', { query }),

  // TV Cast (Chromecast)
  tvDiscover:     ()                  => ipcRenderer.invoke('tv:discover'),
  tvConnect:      (host, port)        => ipcRenderer.invoke('tv:connect', { host, port }),
  tvDisconnect:   ()                  => ipcRenderer.invoke('tv:disconnect'),
  tvStatus:       ()                  => ipcRenderer.invoke('tv:status'),
  tvCastYouTube:  (query)             => ipcRenderer.invoke('tv:cast-youtube', { query }),
  tvCastMedia:    (opts)              => ipcRenderer.invoke('tv:cast-media', opts),
  tvOpenUrl:      (url, title)        => ipcRenderer.invoke('tv:open-url', { url, title }),
  tvVolume:       (level)             => ipcRenderer.invoke('tv:volume', { level }),
  tvMute:         ()                  => ipcRenderer.invoke('tv:mute'),
  tvStop:         ()                  => ipcRenderer.invoke('tv:stop'),
  tvInstallAdb:   ()                  => ipcRenderer.invoke('tv:install-adb'),
  onTvDevicesUpdate: (cb)             => ipcRenderer.on('tv:devices-update', (_e, d) => cb(d)),
  onTvStatusUpdate:  (cb)             => ipcRenderer.on('tv:status-update',  (_e, d) => cb(d)),
  onTvAdbProgress:   (cb)             => ipcRenderer.on('tv:adb-progress',   (_e, d) => cb(d)),
});
