const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('jarvis', {
  onActivated: (cb) => ipcRenderer.on('jarvis:activated', (_e, payload) => cb(payload)),
  transcribe: (audioBase64) => ipcRenderer.invoke('jarvis:transcribe', audioBase64),
  chat: (message, history, attachments) => ipcRenderer.invoke('jarvis:chat', { message, history, attachments: attachments || [] }),
  speak: (text) => ipcRenderer.invoke('jarvis:speak', text),
  openFile: () => ipcRenderer.invoke('jarvis:openFile'),
  notify: (title, body) => ipcRenderer.invoke('jarvis:notify', { title, body }),
  hide: () => ipcRenderer.invoke('jarvis:hide'),
  authSignup: (d) => ipcRenderer.invoke('auth:signup', d),
  authLogin: (d) => ipcRenderer.invoke('auth:login', d),
  authVerify: () => ipcRenderer.invoke('auth:verify'),
  authGoogle: () => ipcRenderer.invoke('auth:google'),
  authLogout: () => ipcRenderer.invoke('auth:logout'),
  // authGetToken intentionally removed — JWT must never cross the IPC bridge to renderer
  onGoogleSuccess: (cb) => ipcRenderer.on('auth:google-success', (_e, d) => cb(d)),
  onSubscriptionActivated: (cb) => ipcRenderer.on('subscription:activated', () => cb()),
  getProfile: () => ipcRenderer.invoke('profile:get'),
  setProfile: (profile) => ipcRenderer.invoke('profile:set', profile),
  getMemories: () => ipcRenderer.invoke('memory:get'),
  clearMemories: () => ipcRenderer.invoke('memory:clear'),
  saveSession: (s) => ipcRenderer.invoke('session:save', s),
  listSessions: () => ipcRenderer.invoke('session:list'),
  deleteSession: (id) => ipcRenderer.invoke('session:delete', id),
  getVoiceSpeed: () => ipcRenderer.invoke('voice:getSpeed'),
  setVoiceSpeed: (s) => ipcRenderer.invoke('voice:setSpeed', s),
  getContacts: () => ipcRenderer.invoke('contacts:get'),
  addContact: (c) => ipcRenderer.invoke('contacts:add', c),
  deleteContact: (id) => ipcRenderer.invoke('contacts:delete', id),
  callContact: (phone, platform) => ipcRenderer.invoke('contacts:call', { phone, platform }),
  openUrl: (url) => ipcRenderer.invoke('jarvis:openUrl', url),
  openCheckout: (plan) => ipcRenderer.invoke('jarvis:openCheckout', plan),
  connectorStatus: () => ipcRenderer.invoke('connector:status'),
  connectorConnect: (service) => ipcRenderer.invoke('connector:connect', service),
  connectorDisconnect: (service) => ipcRenderer.invoke('connector:disconnect', service),
  connectorGetVip: () => ipcRenderer.invoke('connector:getVip'),
  connectorAddVip: (v) => ipcRenderer.invoke('connector:addVip', v),
  connectorRemoveVip: (v) => ipcRenderer.invoke('connector:removeVip', v),
  onConnectorConnected: (cb) => ipcRenderer.on('connector:connected', (_e, d) => cb(d)),
  getMusicService: () => ipcRenderer.sendSync('music:getService'),
  setMusicService: (s) => ipcRenderer.sendSync('music:setService', s),
  getLanguage: () => ipcRenderer.sendSync('language:get'),
  setLanguage: (lang) => ipcRenderer.sendSync('language:set', lang),
  onActionFired: (cb) => ipcRenderer.on('jarvis:action-fired', (_e, d) => cb(d)),
  onVoiceTrigger: (cb) => ipcRenderer.on('jarvis:voice-trigger', () => cb()),
  onSentenceAudio: (cb) => ipcRenderer.on('jarvis:sentence-audio', (_e, d) => cb(d)),
  driveSearch: (query) => ipcRenderer.invoke('drive:search', query),
  driveOpen: (fileId, mimeType, webViewLink) => ipcRenderer.invoke('drive:open', { fileId, mimeType, webViewLink }),
  analyticsGet: (platform) => ipcRenderer.invoke('analytics:get', platform || 'all'),
  reminderList: () => ipcRenderer.invoke('reminder:list'),
  reminderAdd: (r) => ipcRenderer.invoke('reminder:add', r),
  reminderDelete: (id) => ipcRenderer.invoke('reminder:delete', id),
  onReminder: (cb) => ipcRenderer.on('jarvis:reminder', (_e, d) => cb(d)),
  calendarList: () => ipcRenderer.invoke('calendar:list'),
  calendarAdd: (event) => ipcRenderer.invoke('calendar:add', event),
  financeGetStock: (symbol) => ipcRenderer.invoke('finance:getStock', symbol),
  financeResolve: (query) => ipcRenderer.invoke('finance:resolve', query),
  financePortfolio: () => ipcRenderer.invoke('finance:portfolio'),
  financeAdd: (symbol) => ipcRenderer.invoke('finance:add', symbol),
  financeRemove: (symbol) => ipcRenderer.invoke('finance:remove', symbol),
  shopifyConnect: (shop, access_token) => ipcRenderer.invoke('shopify:connect', { shop, access_token }),
  squarespaceConnect: (api_key) => ipcRenderer.invoke('squarespace:connect', { api_key }),
  stripeConnect: (secret_key) => ipcRenderer.invoke('stripe:connect', { secret_key }),
  // Auto-updater
  installUpdate: () => ipcRenderer.send('update:install'),
  onUpdateAvailable: (cb) => ipcRenderer.on('update:available', (_e, d) => cb(d)),
  onUpdateReady: (cb) => ipcRenderer.on('update:ready', () => cb()),
  sendEmail: (opts) => ipcRenderer.invoke('email:send', opts),
  saveWordDoc: (d) => ipcRenderer.invoke('jarvis:saveWordDoc', d),
  openGoogleDoc: (d) => ipcRenderer.invoke('jarvis:openGoogleDoc', d),
  onClipboardAI: (cb) => ipcRenderer.on('jarvis:clipboard-ai', (_e, d) => cb(d)),
});
